## 各个环境都一样的属性在这里定义
spring:
 profiles:
   active: test
 thymeleaf:
     cache: false
 resources:
 static-locations: classpath:/static
server:
  port: 8010
  compression:
    enabled: true
    min-response-size: 2048
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
  tomcat:
    max-http-post-size: 10240000
    max-threads: 1024
    min-spare-threads: 20
  max-http-header-size: 101400
mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  config-location: classpath:mybatis/mybatis-config.xml
logging:
  file: logs/report-center.log
  level:
    org:
      apache:
        commons:
          jexl2: error
export:
  report:
    sxd:
      productId: 76
