package mysql.test.mapper;

import mysql.test.pojo.AccountWorkflow;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface AccountWorkflowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_workflow
     *
     * @mbg.generated Thu May 30 13:33:20 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_workflow
     *
     * @mbg.generated Thu May 30 13:33:20 CST 2019
     */
    int insert(AccountWorkflow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_workflow
     *
     * @mbg.generated Thu May 30 13:33:20 CST 2019
     */
    int insertSelective(AccountWorkflow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_workflow
     *
     * @mbg.generated Thu May 30 13:33:20 CST 2019
     */
    AccountWorkflow selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_workflow
     *
     * @mbg.generated Thu May 30 13:33:20 CST 2019
     */
    int updateByPrimaryKeySelective(AccountWorkflow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_workflow
     *
     * @mbg.generated Thu May 30 13:33:20 CST 2019
     */
    int updateByPrimaryKey(AccountWorkflow record);

    List<AccountWorkflow> selectBySelective(AccountWorkflow accountWorkflow);
}